#!/usr/bin/env perl
use Mojolicious::Lite;

my @entries = (); # 空の配列を宣言

get '/' => sub {
  my $self = shift;
  $self->stash(entries => \@entries); # 配列のリファレンスをテンプレートに渡す
  $self->render('index');
};

post '/message' => sub {
  my $self = shift;
  my $name    = $self->param('name');
  my $mail    = $self->param('mail');
  my $message = $self->param('message');
  my $entry   = {
    name    => $name,
    mail    => $mail,
    message => $message,
  }; # 配列に格納
  if ($mail eq 'age') {
    unshift @entries, $entry;
  } else {
    push @entries, $entry;
  }

  $self->redirect_to('/');
};

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'かんたん掲示板';
<form class="form-horizontal" role="form" method="POST" action="/message">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input name="name" type="text" class="form-control" id="name" placeholder="Name">
    </div>
  </div>
  <div class="form-group">
    <label for="mail" class="col-sm-2 control-label">Mail</label>
    <div class="col-sm-10">
      <input name="mail" type="text" class="form-control" id="mail" placeholder="Mail">
    </div>
  </div>
  <div class="form-group">
    <label for="message" class="col-sm-2 control-label">Message</label>
    <div class="col-sm-10">
      <input name="message" type="text" class="form-control" id="message" placeholder="Message">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">投稿</button>
    </div>
  </div>
</form>

% for my $entry (@{$entries}) {
    <p><a href="mailto:<%= $entry->{mail} %>"><%= $entry->{name} %></a></p>
    <p><%= $entry->{message} %></p>
    <hr>
% }

@@ layouts/default.html.ep
<!DOCTYPE html>

<html>
  <head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <title><%= title %></title>
    <style>
body {
  padding-top: 100px;
}
.starter-template {
  padding: 40px 15px;
  text-align: center;
}
    </style>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <%= content %>
    </div><!-- /.container -->
  </body>
</html>
